// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.chenglun.grpc.hello;

public interface HelloGreetingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.HelloGreeting)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
